# Site settings
title: gentoo.de

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "tyrian"

# No slash at the end
cdnurl: https://1b9a50f4f9de4348cd9f-e703bc50ba0aa66772a874f8c7698be7.ssl.cf5.rackcdn.com
contact: https://www.gentoo.org/main/en/contact.xml
copyrightyears: "2001&ndash;2018"
